version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /app/docker/username
    DOCKER_REGISTRY_PASSWORD: /app/docker/password
    DOCKER_REGISTRY_URL: /app/docker/url
    

phases:
  install:
    runtime-versions:
      python: 3.12
      
  pre_build:
    commands:
      - echo "Installing dependencies"
      - "pip install -r requirements.txt"
      
  build:
    commands:
       - echo "Building Image"
       - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin "$DOCKER_REGISTRY_URL"
       - docker build -t "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/awscodepipeline-pythonproject:latest" .
       - docker push "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/awscodepipeline-pythonproject:latest"
  post_build:
    commands:
       - echo "Build Completed Successfully"
